version: '2'

services:
    web:
        build: .
        ports:
            - "80:5000"
        volumes:
            - /d/DOCKER/cloudFlaskApi:/opt/cloudFlask-api #local directory
        links:
            - db:mongodb
        container_name: cloudFlask_web_1
        depends_on:
            - db
    db:
        image: mongo:3.0.2
        container_name: cloudFlask_db_1